name: TiDa-App

on:
  push:
    branches: [dev]

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - uses: Allviss0211/tida@v7